# Description:

# data path settings
Resources:
  Windows:
    DataBasePath: '~\Documents\libdata.db'
    DataPath: 'C:\NutStore\MyCloud\学术\persisted_libdata'
  MacOS:
  LibDataPath:
  RawDataPath: '/Users/mingo/WeiYun/胡代平/persisted_libdata/raw_data'
  RawDataList:
    - "2016-11-16-guanyuan2013.txt"
    - "2016-11-16-guanyuan2014.txt"
    - "2016-11-16-guanyuan2015.txt"
  MacDataPath: "~/Documents/persisted_libdata"

# log settings
Log:
  # debug/info
  LogLevel:  debug
